[directory]
style = "yellow"
truncation_length = 2

[git_branch]
symbol = "ğŸŒ¿ "

[git_status]
conflicted = "â‰ "
ahead = "â†‘"
behind = "â†“"
staged = "+"
deleted = "âœ˜"
modified = "~"
untracked = "?"

[character]
success_symbol = "[â¯](bold green) "
error_symbol = "[â¯](bold red) "
